# Generated by Django 4.2.16 on 2026-03-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rules', models.JSONField()),
                ('department', models.ForeignKey(blank=True, db_column='departmentId', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('SICK_LEAVE', 'Sick Leave'), ('ANNUAL_LEAVE', 'Annual Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('OTHER', 'Other')], db_column='leaveType', max_length=50)),
                ('start_date', models.DateField(db_column='startDate')),
                ('end_date', models.DateField(db_column='endDate')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('applied_policy', models.ForeignKey(blank=True, db_column='appliedPolicyId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.policy')),
                ('approved_by', models.ForeignKey(blank=True, db_column='approvedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
