# Generated by Django 4.2.16 on 2026-03-12 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_serial', models.CharField(db_column='device_Serial', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_column='ipAddress', unique=True)),
                ('port', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('CHECK_IN', 'Check-in'), ('CHECK_OUT', 'Check-out')], max_length=50)),
                ('status', models.CharField(choices=[('ON_TIME', 'On-time'), ('LATE', 'Late'), ('EARLY_EXIT', 'Early-exit')], max_length=50)),
                ('device', models.ForeignKey(blank=True, db_column='deviceId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.device')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
