# Generated by Django 4.2.16 on 2026-03-13 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(db_column='_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('PERFORMANCE', 'Performance'), ('LEAVE', 'Leave')], max_length=50)),
                ('parameters', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='generatedAt')),
            ],
        ),
    ]
